apiVersion: v1
kind: Pod
metadata:
  name: mahdi-pod
  labels:
    project: lab1_step3 
spec:
  containers:
  - name: lab1step3-container
    image: mahdi36/lab1_step3:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    ports:
    - containerPort: 80

